CREATE TABLE IF NOT EXISTS ativos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    service_tag TEXT UNIQUE,
    empresa TEXT,
    entrega TEXT,
    filial_atual TEXT,
    tipo TEXT,
    modelo TEXT,
    colaborador TEXT,
    duplicado TEXT,
    status TEXT,
    cargo TEXT,
    ultimo_colaborador TEXT,
    multi_usuario TEXT,
    observacao TEXT,
    service_tag_monitor TEXT,
    cc TEXT,
    cc_contab TEXT,
    desc_cc_contab TEXT,
    emp_colab TEXT,
    filial_colab TEXT,
    filial_rh_corrigido TEXT,
    coluna2 TEXT,
    cc_dif TEXT,
    filial_dif TEXT,
    nf_transf TEXT,
    filial_dest_transf TEXT,
    order_sale TEXT,
    remessa TEXT,
    contrato TEXT,
    patrimonio TEXT,
    envio_dell TEXT,
    fim_garantia TEXT,
    tempo_computador TEXT,
    tempo_garantia TEXT,
    reportado_inventario TEXT,
    usuario_inventario TEXT,
    memoria TEXT,
    memoria_adicional TEXT,
    localizacao TEXT,
    troca_chg_2_leva_2025 TEXT,
    x TEXT,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);